// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSA16qsztuSb5odrdVMk8XIl3-niDUBdw',
    appId: '1:320089126273:web:36d9f8e94c4a9c3bb6e480',
    messagingSenderId: '320089126273',
    projectId: 'financeiro-familiar-11f38',
    authDomain: 'financeiro-familiar-11f38.firebaseapp.com',
    storageBucket: 'financeiro-familiar-11f38.firebasestorage.app',
    measurementId: 'G-Q8E2WM3LM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSA16qsztuSb5odrdVMk8XIl3-niDUBdw',
    appId: '1:320089126273:android:36d9f8e94c4a9c3bb6e480',
    messagingSenderId: '320089126273',
    projectId: 'financeiro-familiar-11f38',
    storageBucket: 'financeiro-familiar-11f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSA16qsztuSb5odrdVMk8XIl3-niDUBdw',
    appId: '1:320089126273:ios:36d9f8e94c4a9c3bb6e480',
    messagingSenderId: '320089126273',
    projectId: 'financeiro-familiar-11f38',
    storageBucket: 'financeiro-familiar-11f38.firebasestorage.app',
    iosBundleId: 'com.example.financeiroFamiliar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSA16qsztuSb5odrdVMk8XIl3-niDUBdw',
    appId: '1:320089126273:macos:36d9f8e94c4a9c3bb6e480',
    messagingSenderId: '320089126273',
    projectId: 'financeiro-familiar-11f38',
    storageBucket: 'financeiro-familiar-11f38.firebasestorage.app',
    iosBundleId: 'com.example.financeiroFamiliar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSA16qsztuSb5odrdVMk8XIl3-niDUBdw',
    appId: '1:320089126273:windows:36d9f8e94c4a9c3bb6e480',
    messagingSenderId: '320089126273',
    projectId: 'financeiro-familiar-11f38',
    authDomain: 'financeiro-familiar-11f38.firebaseapp.com',
    storageBucket: 'financeiro-familiar-11f38.firebasestorage.app',
  );
}